import type { Category, Product, StoreSnapshot, Variant } from '@/types'

/* Plantilla demo: Ámbar, casa de perfumería de nicho. */

const u = (id: string) => `unsplash:${id}`

const IMG = {
  hero: u('photo-1774682060997-f8959850a7d4'),
  heroAlt: u('photo-1774682061055-3bfe402e5a12'),
  story: u('photo-1784822041091-604b5172e4d0'),
  ambarNocturno: u('photo-1588405748880-12d1d2a59f75'),
  ambarNocturno2: u('photo-1738414808975-201966230c59'),
  oud: u('photo-1772191399367-91ed8d95664b'),
  oud2: u('photo-1774682060922-c395859148c9'),
  cuero: u('photo-1765031117402-93b2e530edec'),
  rosa: u('photo-1622978147823-33d5e241e976'),
  neroli: u('photo-1594125311687-3b1b3eafa9f4'),
  vetiver: u('photo-1604588638313-882e0e516cfb'),
  azahar: u('photo-1615108395437-df128ad79e80'),
  brisa: u('photo-1608721279136-cd41b752fa41'),
  sandalo: u('photo-1720423514789-15a33e59fc81'),
  vainilla: u('photo-1638295916768-459f6cf440bc'),
  pimienta: u('photo-1733660227168-444e3c751a1e'),
  musgo: u('photo-1716857591457-7d7fa45199c6'),
  iris: u('photo-1733660227163-01bc46e0d7d7'),
  obsidiana: u('photo-1640869116016-93c00ba94b28'),
  setDescubrimiento: u('photo-1623538534120-76d7afaf8eb4'),
  cajaRegalo: u('photo-1617661338085-d1ec6a89a6d8'),
  catElla: u('photo-1630573133526-8d090e0269af'),
  catEl: u('photo-1643797519086-cc9a821fbcfe'),
  catCompartidos: u('photo-1598634222670-87c5f558119c'),
  catRegalos: u('photo-1627823569857-4d8581dc62b2'),
}

/** Tamaños estándar de la casa. El primero es la presentación principal. */
function sizes(price50: number, opts: { stock100?: number | null; sale?: number } = {}): Variant[] {
  const round = (n: number) => Math.round(n / 1000) * 1000
  return [
    {
      id: 'ml50',
      label: '50 ml',
      price: opts.sale ?? price50,
      compareAtPrice: opts.sale ? price50 : undefined,
      stock: 12,
    },
    { id: 'ml100', label: '100 ml', price: round(price50 * 1.5), stock: opts.stock100 ?? 6 },
    { id: 'd5', label: 'Decant 5 ml', price: round(price50 * 0.2), stock: null },
  ]
}

const categories: Category[] = [
  { id: 'ella', slug: 'ella', name: 'Para ella', description: 'Florales luminosos y orientales envolventes.', image: IMG.catElla, order: 1 },
  { id: 'el', slug: 'el', name: 'Para él', description: 'Maderas, cuero y especias con carácter.', image: IMG.catEl, order: 2 },
  { id: 'compartidos', slug: 'compartidos', name: 'Compartidos', description: 'Fragancias sin género, hechas para la piel de quien las lleve.', image: IMG.catCompartidos, order: 3 },
  { id: 'regalos', slug: 'regalos', name: 'Sets y regalos', description: 'Descubre la colección o sorprende a alguien.', image: IMG.catRegalos, order: 4 },
]

const p = (data: Omit<Product, 'active' | 'createdAt' | 'slug'> & { slug?: string; createdAt?: string }): Product => ({
  active: true,
  createdAt: data.createdAt ?? '2026-08-01T10:00:00.000Z',
  slug: data.slug ?? data.id,
  ...data,
})

const products: Product[] = [
  p({
    id: 'ambar-nocturno',
    name: 'Ámbar Nocturno',
    categoryId: 'compartidos',
    summary: 'Resina de ámbar, vainilla negra y un rastro de incienso que dura hasta el amanecer.',
    description:
      'Nuestra fragancia firma. Abre con un destello de bergamota y azafrán, se vuelve cálida con labdanum y rosa de Damasco, y se asienta en un fondo resinoso de ámbar gris, vainilla negra y benjuí. Una estela que la gente recuerda.',
    images: [IMG.ambarNocturno, IMG.ambarNocturno2],
    variants: sizes(320000),
    attributes: {
      familia: 'oriental',
      concentracion: 'edp',
      salida: ['Bergamota', 'Azafrán', 'Pimienta rosa'],
      corazon: ['Labdanum', 'Rosa de Damasco', 'Incienso'],
      fondo: ['Ámbar gris', 'Vainilla negra', 'Benjuí'],
      intensidad: 5,
      duracion: 5,
      estela: 4,
      ocasion: ['noche', 'citas', 'eventos'],
      temporada: ['otono', 'invierno'],
      perfumista: 'Valeria Ospina',
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'oud-imperial',
    name: 'Oud Imperial',
    categoryId: 'el',
    summary: 'Extracto de oud camboyano con cuero ahumado y rosa turca. Edición numerada.',
    description:
      'Un extracto denso y profundo para quienes buscan presencia. El oud camboyano se combina con cuero curtido, rosa turca y un fondo de sándalo de Mysore. Producción limitada a 300 frascos numerados a mano.',
    images: [IMG.oud, IMG.oud2],
    variants: [
      { id: 'ml50', label: 'Extracto 50 ml', price: 540000, stock: 4 },
      { id: 'd5', label: 'Decant 5 ml', price: 98000, stock: null },
    ],
    attributes: {
      familia: 'amaderada',
      concentracion: 'extrait',
      salida: ['Cardamomo', 'Azafrán'],
      corazon: ['Oud camboyano', 'Rosa turca', 'Cuero'],
      fondo: ['Sándalo', 'Pachulí', 'Almizcle'],
      intensidad: 5,
      duracion: 5,
      estela: 5,
      ocasion: ['noche', 'eventos'],
      temporada: ['invierno'],
      perfumista: 'Valeria Ospina',
    },
    badges: ['limitada'],
    featured: true,
  }),
  p({
    id: 'rosa-de-medianoche',
    name: 'Rosa de Medianoche',
    categoryId: 'ella',
    summary: 'Una rosa oscura y aterciopelada, con frambuesa y pachulí.',
    description:
      'La rosa como nunca la habías olido: jugosa al inicio con frambuesa y lichi, aterciopelada en el corazón y misteriosa en el fondo gracias al pachulí y el almizcle blanco.',
    images: [IMG.rosa],
    variants: sizes(285000, { sale: 249000 }),
    attributes: {
      familia: 'floral',
      concentracion: 'edp',
      salida: ['Frambuesa', 'Lichi'],
      corazon: ['Rosa búlgara', 'Peonía'],
      fondo: ['Pachulí', 'Almizcle blanco'],
      intensidad: 3,
      duracion: 4,
      estela: 3,
      ocasion: ['citas', 'noche'],
      temporada: ['otono', 'primavera'],
      perfumista: 'Tomás Rendón',
    },
    badges: ['oferta'],
    featured: true,
  }),
  p({
    id: 'neroli-del-caribe',
    name: 'Neroli del Caribe',
    categoryId: 'compartidos',
    summary: 'Azahar, lima y sal marina. Un mediodía frente al mar en un frasco.',
    description:
      'Fresca, luminosa y fácil de llevar. Neroli tunecino, lima de Tahití y un acorde salino que recuerda la piel después del mar. Ideal para el calor y para la oficina.',
    images: [IMG.neroli],
    variants: sizes(229000),
    attributes: {
      familia: 'citrica',
      concentracion: 'edt',
      salida: ['Lima', 'Bergamota', 'Mandarina verde'],
      corazon: ['Neroli', 'Flor de azahar'],
      fondo: ['Sal marina', 'Almizcle', 'Ámbar blanco'],
      intensidad: 2,
      duracion: 3,
      estela: 2,
      ocasion: ['dia', 'oficina'],
      temporada: ['primavera', 'verano'],
      perfumista: 'Tomás Rendón',
    },
    badges: ['nuevo'],
    featured: true,
    createdAt: '2026-09-20T10:00:00.000Z',
  }),
  p({
    id: 'cuero-salvaje',
    name: 'Cuero Salvaje',
    categoryId: 'el',
    summary: 'Cuero gamuzado, tabaco rubio y un toque de whisky.',
    description:
      'Inspirado en los viejos clubes de lectura: cuero suave como la gamuza, hojas de tabaco rubio, un chorrito de whisky y maderas tostadas. Elegante sin esfuerzo.',
    images: [IMG.cuero],
    variants: sizes(299000),
    attributes: {
      familia: 'especiada',
      concentracion: 'edp',
      salida: ['Whisky', 'Pimienta negra'],
      corazon: ['Tabaco rubio', 'Cuero gamuzado'],
      fondo: ['Cedro', 'Vetiver', 'Haba tonka'],
      intensidad: 4,
      duracion: 4,
      estela: 3,
      ocasion: ['noche', 'oficina'],
      temporada: ['otono', 'invierno'],
      perfumista: 'Valeria Ospina',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'vetiver-ahumado',
    name: 'Vetiver Ahumado',
    categoryId: 'el',
    summary: 'Vetiver de Haití, té lapsang y madera de guayaco.',
    description:
      'Seco, terroso y con un humo sutil de té lapsang souchong. Un amaderado moderno para quienes prefieren lo discreto pero inolvidable.',
    images: [IMG.vetiver],
    variants: sizes(275000),
    attributes: {
      familia: 'amaderada',
      concentracion: 'edp',
      salida: ['Pomelo', 'Jengibre'],
      corazon: ['Té lapsang', 'Vetiver de Haití'],
      fondo: ['Guayaco', 'Musgo de roble'],
      intensidad: 3,
      duracion: 4,
      estela: 3,
      ocasion: ['dia', 'oficina'],
      temporada: ['otono', 'invierno', 'primavera'],
      perfumista: 'Tomás Rendón',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'flor-de-azahar',
    name: 'Flor de Azahar',
    categoryId: 'ella',
    summary: 'Azahar, jazmín sambac y miel blanca. Luminoso y romántico.',
    description:
      'Un ramo blanco recién cortado: azahar, jazmín sambac y tuberosa sobre una base suave de miel blanca y almizcle. Perfecto para bodas y mañanas de domingo.',
    images: [IMG.azahar],
    variants: sizes(265000),
    attributes: {
      familia: 'floral',
      concentracion: 'edp',
      salida: ['Pera', 'Bergamota'],
      corazon: ['Azahar', 'Jazmín sambac', 'Tuberosa'],
      fondo: ['Miel blanca', 'Almizcle'],
      intensidad: 3,
      duracion: 3,
      estela: 3,
      ocasion: ['dia', 'citas', 'eventos'],
      temporada: ['primavera', 'verano'],
      perfumista: 'Valeria Ospina',
    },
    badges: ['top'],
    featured: false,
  }),
  p({
    id: 'brisa-del-pacifico',
    name: 'Brisa del Pacífico',
    categoryId: 'compartidos',
    summary: 'Acorde marino, salvia y madera de deriva.',
    description:
      'Un acuático sin clichés: algas, salvia esclarea y madera de deriva blanqueada por el sol. Limpio, mineral y muy cómodo de llevar.',
    images: [IMG.brisa],
    variants: sizes(219000),
    attributes: {
      familia: 'acuatica',
      concentracion: 'edt',
      salida: ['Acorde marino', 'Limón'],
      corazon: ['Salvia esclarea', 'Algas'],
      fondo: ['Madera de deriva', 'Ámbar gris'],
      intensidad: 2,
      duracion: 3,
      estela: 2,
      ocasion: ['dia', 'oficina'],
      temporada: ['verano'],
      perfumista: 'Tomás Rendón',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'sandalo-blanco',
    name: 'Sándalo Blanco',
    categoryId: 'compartidos',
    summary: 'Sándalo cremoso, leche de higo y cedro. Una segunda piel.',
    description:
      'Cremoso, suave y adictivo. Sándalo australiano, leche de higo y cedro del Atlas. Se funde con la piel y huele distinto en cada persona.',
    images: [IMG.sandalo],
    variants: sizes(259000),
    attributes: {
      familia: 'amaderada',
      concentracion: 'edp',
      salida: ['Higo', 'Cardamomo'],
      corazon: ['Leche de higo', 'Iris'],
      fondo: ['Sándalo australiano', 'Cedro del Atlas'],
      intensidad: 2,
      duracion: 4,
      estela: 2,
      ocasion: ['dia', 'oficina', 'citas'],
      temporada: ['primavera', 'otono'],
      perfumista: 'Valeria Ospina',
    },
    badges: ['nuevo'],
    featured: true,
    createdAt: '2026-09-12T10:00:00.000Z',
  }),
  p({
    id: 'vainilla-bourbon',
    name: 'Vainilla Bourbon',
    categoryId: 'ella',
    summary: 'Vainilla de Madagascar, caramelo salado y ron añejo.',
    description:
      'Un gourmand adulto: vainilla bourbon de Madagascar, caramelo con sal y un toque de ron añejo sobre maderas tostadas. Dulce, pero nunca empalagoso.',
    images: [IMG.vainilla],
    variants: sizes(249000),
    attributes: {
      familia: 'gourmand',
      concentracion: 'edp',
      salida: ['Ron añejo', 'Mandarina'],
      corazon: ['Caramelo salado', 'Heliotropo'],
      fondo: ['Vainilla de Madagascar', 'Haba tonka'],
      intensidad: 4,
      duracion: 5,
      estela: 4,
      ocasion: ['noche', 'citas'],
      temporada: ['otono', 'invierno'],
      perfumista: 'Tomás Rendón',
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'pimienta-rosa',
    name: 'Pimienta Rosa',
    categoryId: 'compartidos',
    summary: 'Pimienta rosa, cardamomo y madera de cachemira.',
    description:
      'Chispeante y cálida a la vez. Pimienta rosa y cardamomo verde sobre un fondo suave de madera de cachemira y almizcle.',
    images: [IMG.pimienta],
    variants: sizes(239000, { stock100: 0 }),
    attributes: {
      familia: 'especiada',
      concentracion: 'edp',
      salida: ['Pimienta rosa', 'Cardamomo'],
      corazon: ['Iris', 'Violeta'],
      fondo: ['Madera de cachemira', 'Almizcle'],
      intensidad: 3,
      duracion: 3,
      estela: 3,
      ocasion: ['dia', 'oficina'],
      temporada: ['primavera', 'otono'],
      perfumista: 'Valeria Ospina',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'musgo-y-lluvia',
    name: 'Musgo y Lluvia',
    categoryId: 'compartidos',
    summary: 'Tierra mojada, musgo de roble y hojas de violeta.',
    description:
      'El olor del bosque después de la lluvia: petricor, hojas de violeta, musgo de roble y pachulí. Un chipre verde, elegante y muy nuestro.',
    images: [IMG.musgo],
    variants: sizes(269000),
    attributes: {
      familia: 'chipre',
      concentracion: 'edp',
      salida: ['Petricor', 'Hojas de violeta'],
      corazon: ['Geranio', 'Helecho'],
      fondo: ['Musgo de roble', 'Pachulí'],
      intensidad: 3,
      duracion: 4,
      estela: 3,
      ocasion: ['dia', 'oficina'],
      temporada: ['otono', 'primavera'],
      perfumista: 'Tomás Rendón',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'iris-poudre',
    name: 'Iris Poudré',
    categoryId: 'ella',
    summary: 'Iris pallida, almendra y un velo de polvos de arroz.',
    description:
      'Empolvado, sofisticado y suave como el cachemir. Mantequilla de iris, almendra amarga y heliotropo sobre almizcles limpios.',
    images: [IMG.iris],
    variants: sizes(289000),
    attributes: {
      familia: 'floral',
      concentracion: 'edp',
      salida: ['Almendra amarga', 'Aldehídos'],
      corazon: ['Iris pallida', 'Heliotropo'],
      fondo: ['Almizcle', 'Polvo de arroz'],
      intensidad: 2,
      duracion: 4,
      estela: 2,
      ocasion: ['oficina', 'dia'],
      temporada: ['primavera', 'otono'],
      perfumista: 'Valeria Ospina',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'elixir-obsidiana',
    name: 'Elixir Obsidiana',
    categoryId: 'el',
    summary: 'Incienso, pimienta negra y maderas quemadas. Oscuro y magnético.',
    description:
      'Un extracto nocturno de incienso de Omán, pimienta negra y madera de abedul quemada, suavizado por ámbar y cuero. Hecho para dejar huella.',
    images: [IMG.obsidiana],
    variants: [
      { id: 'ml50', label: 'Extracto 50 ml', price: 459000, stock: 7 },
      { id: 'd5', label: 'Decant 5 ml', price: 82000, stock: null },
    ],
    attributes: {
      familia: 'oriental',
      concentracion: 'extrait',
      salida: ['Pimienta negra', 'Elemí'],
      corazon: ['Incienso de Omán', 'Abedul'],
      fondo: ['Ámbar', 'Cuero', 'Labdanum'],
      intensidad: 5,
      duracion: 5,
      estela: 4,
      ocasion: ['noche', 'eventos'],
      temporada: ['invierno', 'otono'],
      perfumista: 'Tomás Rendón',
    },
    badges: ['nuevo'],
    featured: false,
    createdAt: '2026-09-28T10:00:00.000Z',
  }),
  p({
    id: 'set-descubrimiento',
    name: 'Set Descubrimiento',
    categoryId: 'regalos',
    summary: 'Seis decants de 5 ml para encontrar tu firma. El valor se descuenta de tu primer frasco.',
    description:
      'La mejor forma de conocer la casa. Elige seis fragancias de la colección en formato de 5 ml, presentadas en un estuche de cartón reciclado con tarjetas de notas. Si luego compras un frasco de 50 o 100 ml, te descontamos el valor del set.',
    images: [IMG.setDescubrimiento],
    variants: [{ id: 'set6', label: '6 × 5 ml', price: 189000, compareAtPrice: 228000, stock: 20 }],
    attributes: {
      familia: 'oriental',
      concentracion: 'edp',
      ocasion: ['dia', 'noche'],
      temporada: ['primavera', 'verano', 'otono', 'invierno'],
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'caja-regalo-firma',
    name: 'Caja Regalo Firma',
    categoryId: 'regalos',
    summary: 'Ámbar Nocturno 50 ml, vela de ámbar y tarjeta escrita a mano.',
    description:
      'Nuestro regalo más pedido: un frasco de Ámbar Nocturno de 50 ml, una vela perfumada de 180 g con el mismo acorde y una tarjeta escrita a mano con tu mensaje. Llega envuelta y lista para entregar.',
    images: [IMG.cajaRegalo],
    variants: [{ id: 'caja', label: 'Caja completa', price: 389000, compareAtPrice: 420000, stock: 8 }],
    attributes: {
      familia: 'oriental',
      concentracion: 'edp',
      ocasion: ['eventos', 'citas'],
      temporada: ['otono', 'invierno'],
    },
    badges: ['oferta'],
    featured: false,
  }),
]

export const ambarTemplate: StoreSnapshot = {
  categories,
  products,
  config: {
    id: 'ambar',
    business: {
      name: 'Ámbar',
      tagline: 'Casa de perfumería de nicho',
      logoText: 'Ámbar',
      whatsapp: '573001234567',
      instagram: 'ambar.perfumeria',
      email: 'hola@ambar.demo',
      address: 'Calle 69A #5-32, Zona G',
      city: 'Bogotá',
      hours: 'Lun a sáb · 10:00 a 20:00',
      floatingWhatsapp: false,
      currency: 'COP',
      locale: 'es-CO',
    },
    theme: {
      mode: 'dark',
      colors: {
        bg: '#0f0d0b',
        surface: '#1a1714',
        ink: '#f3eadb',
        muted: '#a3967f',
        accent: '#c9a35b',
        accentInk: '#14110d',
        line: '#2e2822',
      },
      fonts: { display: 'Cormorant Garamond', body: 'Manrope' },
      radius: 2,
      buttonShape: 'square',
      displayWeight: 400,
      displayItalic: false,
      cardRatio: '3/4',
      cardStyle: 'editorial',
      grain: true,
      logoStyle: 'caps',
    },
    catalog: {
      productNoun: { singular: 'fragancia', plural: 'fragancias' },
      variantLabel: 'Presentación',
      groups: [
        { id: 'piramide', label: 'Pirámide olfativa', layout: 'tiers', tierLabels: ['Salida', 'Corazón', 'Fondo'] },
        { id: 'perfil', label: 'Perfil', layout: 'meters' },
        { id: 'uso', label: 'Cuándo llevarlo', layout: 'chips' },
        { id: 'ficha', label: 'Ficha', layout: 'list' },
      ],
      attributes: [
        {
          id: 'familia',
          label: 'Familia olfativa',
          type: 'select',
          filterable: true,
          showOnCard: true,
          group: 'ficha',
          options: [
            { value: 'amaderada', label: 'Amaderada', color: '#8a6a4a' },
            { value: 'oriental', label: 'Oriental', color: '#c9a35b' },
            { value: 'floral', label: 'Floral', color: '#d98ca0' },
            { value: 'citrica', label: 'Cítrica', color: '#e3c55a' },
            { value: 'acuatica', label: 'Acuática', color: '#6aa3b8' },
            { value: 'gourmand', label: 'Gourmand', color: '#b0703d' },
            { value: 'chipre', label: 'Chipre', color: '#6f8a5a' },
            { value: 'especiada', label: 'Especiada', color: '#b5523a' },
          ],
        },
        {
          id: 'concentracion',
          label: 'Concentración',
          type: 'select',
          group: 'ficha',
          filterable: true,
          options: [
            { value: 'edt', label: 'Eau de Toilette' },
            { value: 'edp', label: 'Eau de Parfum' },
            { value: 'extrait', label: 'Extracto' },
          ],
        },
        { id: 'salida', label: 'Notas de salida', type: 'tags', group: 'piramide' },
        { id: 'corazon', label: 'Notas de corazón', type: 'tags', group: 'piramide' },
        { id: 'fondo', label: 'Notas de fondo', type: 'tags', group: 'piramide' },
        { id: 'intensidad', label: 'Intensidad', type: 'scale', max: 5, scaleLabels: ['Suave', 'Intensa'], group: 'perfil', filterable: true },
        { id: 'duracion', label: 'Duración', type: 'scale', max: 5, scaleLabels: ['2 h', '12 h+'], group: 'perfil' },
        { id: 'estela', label: 'Estela', type: 'scale', max: 5, scaleLabels: ['Íntima', 'Envolvente'], group: 'perfil' },
        {
          id: 'ocasion',
          label: 'Ocasión',
          type: 'multi',
          filterable: true,
          group: 'uso',
          options: [
            { value: 'dia', label: 'Día' },
            { value: 'noche', label: 'Noche' },
            { value: 'oficina', label: 'Oficina' },
            { value: 'citas', label: 'Citas' },
            { value: 'eventos', label: 'Eventos' },
          ],
        },
        {
          id: 'temporada',
          label: 'Temporada',
          type: 'multi',
          filterable: true,
          group: 'uso',
          options: [
            { value: 'primavera', label: 'Primavera' },
            { value: 'verano', label: 'Verano' },
            { value: 'otono', label: 'Otoño' },
            { value: 'invierno', label: 'Invierno' },
          ],
        },
        { id: 'perfumista', label: 'Perfumista', type: 'text', group: 'ficha' },
      ],
      badges: [
        { id: 'nuevo', label: 'Nuevo', tone: 'accent' },
        { id: 'top', label: 'Más vendido', tone: 'ink' },
        { id: 'limitada', label: 'Edición limitada', tone: 'accent' },
        { id: 'oferta', label: 'Oferta', tone: 'soft' },
      ],
    },
    sections: [
      {
        id: 'hero',
        type: 'hero',
        enabled: true,
        props: {
          layout: 'immersive',
          eyebrow: 'Perfumería de nicho · Bogotá',
          title: 'Fragancias que se quedan contigo',
          subtitle:
            'Composiciones de autor creadas en pequeños lotes, con materias primas nobles y una estela que la gente recuerda.',
          image: IMG.hero,
          ctaLabel: 'Explorar la colección',
          secondaryLabel: 'Asesoría por WhatsApp',
        },
      },
      {
        id: 'marquee',
        type: 'marquee',
        enabled: true,
        props: {
          items: ['Oud camboyano', 'Ámbar gris', 'Vainilla de Madagascar', 'Neroli tunecino', 'Iris pallida', 'Sándalo de Mysore', 'Incienso de Omán'],
        },
      },
      {
        id: 'destacados',
        type: 'products',
        enabled: true,
        props: { title: 'Los más deseados', subtitle: 'Las fragancias que más piden nuestros clientes.', source: 'featured', limit: 4 },
      },
      {
        id: 'categorias',
        type: 'categories',
        enabled: true,
        props: { title: 'Encuentra tu firma', subtitle: 'Cuatro caminos para empezar.' },
      },
      {
        id: 'historia',
        type: 'story',
        enabled: true,
        props: {
          eyebrow: 'La casa',
          title: 'Hechas a mano, en lotes de cien',
          body:
            'Cada fragancia de Ámbar nace en nuestro taller de la Zona G. Maceramos los concentrados durante seis semanas y llenamos cada frasco a mano. Por eso nuestros lotes son pequeños y, a veces, se agotan.',
          image: IMG.story,
          ctaLabel: 'Conoce las novedades',
        },
      },
      {
        id: 'nuevos',
        type: 'products',
        enabled: true,
        props: { title: 'Recién llegados', source: 'new', limit: 4 },
      },
      {
        id: 'beneficios',
        type: 'benefits',
        enabled: true,
        props: {
          items: [
            { icon: 'droplet', title: 'Prueba antes con un decant', text: 'Todas las fragancias tienen versión de 5 ml.' },
            { icon: 'truck', title: 'Envíos a todo el país', text: 'Gratis en Bogotá por compras desde $300.000.' },
            { icon: 'gift', title: 'Envoltura de regalo', text: 'Con tarjeta escrita a mano, sin costo.' },
            { icon: 'message', title: 'Asesoría personal', text: 'Te ayudamos a elegir por WhatsApp.' },
          ],
        },
      },
      {
        id: 'testimonios',
        type: 'testimonials',
        enabled: true,
        props: {
          title: 'Lo que dicen de nosotros',
          items: [
            { quote: 'Me preguntan qué perfume llevo cada vez que uso Ámbar Nocturno. Ya voy por mi tercer frasco.', author: 'Daniela M.', detail: 'Ámbar Nocturno' },
            { quote: 'Pedí el set de descubrimiento sin saber qué buscaba y terminé enamorado del Vetiver Ahumado.', author: 'Andrés R.', detail: 'Set Descubrimiento' },
            { quote: 'La asesoría por WhatsApp fue increíble. Me recomendaron el regalo perfecto para mi mamá.', author: 'Laura G.', detail: 'Caja Regalo Firma' },
          ],
        },
      },
      {
        id: 'faq',
        type: 'faq',
        enabled: true,
        props: {
          title: 'Preguntas frecuentes',
          items: [
            { q: '¿Cómo hago un pedido?', a: 'Agrega las fragancias a tu bolsa y pulsa “Pedir por WhatsApp”. Te llegará el resumen listo para enviar y te confirmamos el pago y el envío en minutos.' },
            { q: '¿Cuánto dura una fragancia?', a: 'Nuestros Eau de Parfum duran entre 6 y 8 horas en piel, y los extractos más de 10. En la ficha de cada fragancia verás su intensidad, duración y estela.' },
            { q: '¿Qué es un decant?', a: 'Es una muestra de 5 ml de la misma fragancia, ideal para probarla varios días antes de comprar el frasco completo.' },
            { q: '¿Hacen envíos fuera de Bogotá?', a: 'Sí, enviamos a toda Colombia con transportadora. El tiempo de entrega es de 2 a 4 días hábiles.' },
          ],
        },
      },
      {
        id: 'cta',
        type: 'cta',
        enabled: true,
        props: {
          title: '¿No sabes cuál elegir?',
          body: 'Cuéntanos qué perfumes te gustan y te recomendamos tu próxima firma.',
          ctaLabel: 'Hablar con un asesor',
        },
      },
    ],
    checkout: {
      orderPrefix: 'AMB',
      greeting: 'Hola Ámbar ✨ Quiero hacer este pedido:',
      closing: '¿Me confirman disponibilidad y el total? ¡Gracias!',
      deliveryOptions: [
        { id: 'tienda', label: 'Recoger en la tienda', fee: 0, requiresAddress: false, note: 'Zona G, Bogotá' },
        { id: 'bogota', label: 'Domicilio en Bogotá', fee: 12000, requiresAddress: true, note: 'Mismo día si pides antes de las 2 p. m.', freeFrom: 300000 },
        { id: 'nacional', label: 'Envío nacional', fee: 18000, requiresAddress: true, note: '2 a 4 días hábiles' },
      ],
      paymentOptions: ['Transferencia o Nequi', 'Tarjeta (link de pago)', 'Efectivo contra entrega'],
    },
    announcements: [
      'Envío gratis en Bogotá por compras desde $300.000',
      'Nuevo: Elixir Obsidiana, extracto de edición limitada',
      'Envoltura de regalo sin costo',
    ],
  },
}
