import type { Category, Product, StoreSnapshot, Variant } from '@/types'

/* Plantilla demo: Lumière, maquillaje y cuidado de la piel. */

const u = (id: string) => `unsplash:${id}`

const IMG = {
  hero: u('photo-1596462502278-27bfdc403348'),
  story: u('photo-1613966802194-d46a163af70d'),
  velvet: u('photo-1625093742435-6fa192b6fb10'),
  swatches: u('photo-1631214499500-2e34edcaccfe'),
  gloss: u('photo-1631214524049-0ebbbe6d81aa'),
  gloss2: u('photo-1631214524115-9942bf927d4a'),
  balsamo: u('photo-1635263282145-253319c75fd4'),
  satin: u('photo-1555050455-f96634b5cba6'),
  satin2: u('photo-1695634503987-f6f18706708e'),
  atardecer: u('photo-1547934659-7fa699ef3ce0'),
  atardecer2: u('photo-1583931537180-7d26921260e4'),
  colorPop: u('photo-1581273154768-0a9a16887d2a'),
  colorPop2: u('photo-1533562389935-457b1ae48a39'),
  mascara: u('photo-1670832209136-fad04d9920f9'),
  mascara2: u('photo-1548902378-2ec44c906391'),
  base: u('photo-1599733589046-10c005739ef9'),
  base2: u('photo-1557205465-f3762edea6d3'),
  corrector: u('photo-1627885793933-584e53987c14'),
  rubor: u('photo-1632322781997-8fb327c7ac9b'),
  rubor2: u('photo-1602558618194-3037081afe0d'),
  iluminador: u('photo-1701271482230-5ecaec3cd3e1'),
  iluminador2: u('photo-1531646317777-0619c7c5d1d3'),
  serumC: u('photo-1638609269435-1b4421f8585c'),
  serumC2: u('photo-1623143445418-40c192fa3d11'),
  hialuronico: u('photo-1710410815589-dd83514104d0'),
  crema: u('photo-1627811015433-368c148f6c3c'),
  brochas: u('photo-1453761816053-ed5ba727b5b7'),
  brochas2: u('photo-1516975080664-ed2fc6a32937'),
  trio: u('photo-1625093525885-282384697917'),
  catLabios: u('photo-1759311712267-7b08c6fe8b17'),
  catOjos: u('photo-1595550912256-b24059bb08e8'),
  catRostro: u('photo-1654973433534-1238e06f6b38'),
  catCuidado: u('photo-1638609269267-f0128098a809'),
  catAccesorios: u('photo-1620464003286-a5b0d79f32c2'),
}

/** Variantes por tono: mismo precio, cada una con su muestra de color. */
function tones(price: number, list: [string, string][], stock = 10): Variant[] {
  return list.map(([label, swatch], i) => ({
    id: `t${i + 1}`,
    label,
    price,
    swatch,
    stock: i === list.length - 1 ? 2 : stock,
  }))
}

const categories: Category[] = [
  { id: 'labios', slug: 'labios', name: 'Labios', description: 'Labiales, glosses y bálsamos con color.', image: IMG.catLabios, order: 1 },
  { id: 'ojos', slug: 'ojos', name: 'Ojos', description: 'Paletas, máscaras y todo para tu mirada.', image: IMG.catOjos, order: 2 },
  { id: 'rostro', slug: 'rostro', name: 'Rostro', description: 'Bases, correctores, rubores e iluminadores.', image: IMG.catRostro, order: 3 },
  { id: 'cuidado', slug: 'cuidado', name: 'Cuidado de la piel', description: 'Sérums y cremas para una piel feliz.', image: IMG.catCuidado, order: 4 },
  { id: 'accesorios', slug: 'accesorios', name: 'Accesorios', description: 'Brochas y herramientas profesionales.', image: IMG.catAccesorios, order: 5 },
]

const p = (data: Omit<Product, 'active' | 'createdAt' | 'slug'> & { slug?: string; createdAt?: string }): Product => ({
  active: true,
  createdAt: data.createdAt ?? '2026-08-01T10:00:00.000Z',
  slug: data.slug ?? data.id,
  ...data,
})

const products: Product[] = [
  p({
    id: 'labial-velvet-kiss',
    name: 'Labial Velvet Kiss',
    categoryId: 'labios',
    summary: 'Mate aterciopelado que no reseca. Color intenso en una sola pasada.',
    description:
      'Nuestro best seller. Una fórmula mate con manteca de karité y vitamina E que se desliza como crema y se seca en un acabado de terciopelo. Hasta 12 horas sin retoques y sin sensación de tirantez.',
    images: [IMG.velvet, IMG.swatches],
    variants: tones(59000, [
      ['Rosé 01', '#c4707a'],
      ['Terracota 02', '#b0533a'],
      ['Berry 03', '#7c2340'],
      ['Nude 04', '#c49481'],
      ['Rojo clásico 05', '#a3192a'],
    ]),
    attributes: {
      acabado: 'mate',
      tipo_piel: ['todo'],
      cobertura: 5,
      duracion: 5,
      hidratacion: 3,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Manteca de karité', 'Vitamina E'],
      libre_de: ['parabenos'],
      contenido: '3,5 g',
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'gloss-cristal',
    name: 'Gloss Cristal',
    categoryId: 'labios',
    summary: 'Brillo efecto espejo que no se siente pegajoso.',
    description:
      'Un gloss con aceite de jojoba y ácido hialurónico que deja los labios jugosos y con brillo de cristal. Úsalo solo o sobre tu labial favorito.',
    images: [IMG.gloss, IMG.gloss2],
    variants: tones(45000, [
      ['Cristal', '#f3dcd8'],
      ['Pink glaze', '#e79ab0'],
      ['Durazno', '#f0a98a'],
    ]),
    attributes: {
      acabado: 'gloss',
      tipo_piel: ['todo'],
      cobertura: 2,
      duracion: 3,
      hidratacion: 5,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Aceite de jojoba', 'Ácido hialurónico'],
      libre_de: ['parabenos', 'fragancia'],
      contenido: '6 ml',
    },
    badges: ['nuevo'],
    featured: true,
    createdAt: '2026-09-22T10:00:00.000Z',
  }),
  p({
    id: 'balsamo-tinte',
    name: 'Bálsamo con Tinte',
    categoryId: 'labios',
    summary: 'Hidratación de 24 horas con un toque de color natural.',
    description:
      'El paso perfecto entre el cuidado y el maquillaje: un bálsamo con aceite de rosa mosqueta que suaviza los labios y les da un rubor natural.',
    images: [IMG.balsamo],
    variants: tones(39000, [
      ['Rosé', '#d98a8e'],
      ['Cereza', '#a8323e'],
    ]),
    attributes: {
      acabado: 'luminoso',
      tipo_piel: ['todo', 'sensible'],
      cobertura: 1,
      duracion: 2,
      hidratacion: 5,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Rosa mosqueta', 'Cera de candelilla'],
      libre_de: ['parabenos', 'fragancia'],
      contenido: '4 g',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'labial-satin-nude',
    name: 'Labial Satin Nude',
    categoryId: 'labios',
    summary: 'Tonos nude satinados pensados para pieles latinas.',
    description:
      'Tres nudes cálidos creados con maquilladoras de Medellín para que nunca te veas apagada. Acabado satinado, cómodo todo el día.',
    images: [IMG.satin, IMG.satin2],
    variants: tones(55000, [
      ['Arena', '#c9a089'],
      ['Canela', '#a8735a'],
      ['Moka', '#7f5141'],
    ]),
    attributes: {
      acabado: 'satinado',
      tipo_piel: ['todo'],
      cobertura: 4,
      duracion: 4,
      hidratacion: 4,
      vegano: false,
      cruelty_free: true,
      ingredientes: ['Aceite de argán'],
      libre_de: ['parabenos'],
      contenido: '3,5 g',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'paleta-atardecer',
    name: 'Paleta Atardecer',
    categoryId: 'ojos',
    summary: '12 sombras cálidas entre mates y brillos. De día a noche en una sola paleta.',
    description:
      'Rosas, duraznos, cobres y un marrón profundo. Seis mates sedosos que se difuminan solos y seis brillos de alto impacto que se aplican con el dedo.',
    images: [IMG.atardecer, IMG.atardecer2],
    variants: [{ id: 'unica', label: '12 tonos', price: 119000, compareAtPrice: 139000, stock: 9 }],
    attributes: {
      acabado: 'satinado',
      tipo_piel: ['todo'],
      cobertura: 4,
      duracion: 4,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Mica natural', 'Vitamina E'],
      libre_de: ['parabenos', 'fragancia'],
      contenido: '12 × 1,2 g',
    },
    badges: ['top', 'oferta'],
    featured: true,
  }),
  p({
    id: 'paleta-color-pop',
    name: 'Paleta Color Pop',
    categoryId: 'ojos',
    summary: 'Pigmentos vibrantes para looks atrevidos.',
    description:
      'Dieciséis colores saturados, del fucsia al turquesa, con pigmentación máxima y cero caída. Para cuando el maquillaje es tu forma de jugar.',
    images: [IMG.colorPop, IMG.colorPop2],
    variants: [{ id: 'unica', label: '16 tonos', price: 99000, stock: 6 }],
    attributes: {
      acabado: 'mate',
      tipo_piel: ['todo'],
      cobertura: 5,
      duracion: 4,
      vegano: true,
      cruelty_free: true,
      libre_de: ['parabenos'],
      contenido: '16 × 0,8 g',
    },
    badges: ['nuevo'],
    featured: false,
    createdAt: '2026-09-18T10:00:00.000Z',
  }),
  p({
    id: 'mascara-volumen',
    name: 'Máscara Volumen Infinito',
    categoryId: 'ojos',
    summary: 'Volumen y longitud sin grumos. Resistente al agua y al llanto de las bodas.',
    description:
      'Cepillo de fibra con forma de reloj de arena que separa cada pestaña y una fórmula con cera de arroz que da volumen sin pesar. Se retira con agua tibia.',
    images: [IMG.mascara, IMG.mascara2],
    variants: tones(65000, [
      ['Negro intenso', '#141414'],
      ['Café', '#4a2e22'],
    ]),
    attributes: {
      acabado: 'natural',
      tipo_piel: ['todo', 'sensible'],
      cobertura: 4,
      duracion: 5,
      vegano: false,
      cruelty_free: true,
      ingredientes: ['Cera de arroz', 'Pantenol'],
      libre_de: ['parabenos'],
      contenido: '9 ml',
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'base-segunda-piel',
    name: 'Base Segunda Piel',
    categoryId: 'rostro',
    summary: 'Cobertura media modulable con acabado de piel real.',
    description:
      'Una base ligera con niacinamida y protección SPF 20 que unifica el tono sin cubrir tu piel. Se adapta a tu tono en minutos y dura todo el día sin oxidarse.',
    images: [IMG.base, IMG.base2],
    variants: tones(89000, [
      ['110 Porcelana', '#f1d3bc'],
      ['220 Marfil', '#e6bf9f'],
      ['330 Beige', '#d4a47c'],
      ['440 Miel', '#b98058'],
      ['550 Canela', '#8c5a3c'],
    ]),
    attributes: {
      acabado: 'natural',
      tipo_piel: ['mixta', 'grasa', 'seca'],
      cobertura: 3,
      duracion: 4,
      hidratacion: 3,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Niacinamida', 'SPF 20'],
      libre_de: ['parabenos', 'siliconas'],
      contenido: '30 ml',
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'corrector-luz',
    name: 'Corrector Luz',
    categoryId: 'rostro',
    summary: 'Ilumina ojeras y cubre imperfecciones sin marcar líneas.',
    description:
      'Cobertura alta con textura cremosa y cafeína para desinflamar la zona de las ojeras. Un toque basta.',
    images: [IMG.corrector],
    variants: tones(62000, [
      ['Claro', '#f0d2b8'],
      ['Medio', '#d6a47e'],
      ['Profundo', '#9a6845'],
    ]),
    attributes: {
      acabado: 'natural',
      tipo_piel: ['todo'],
      cobertura: 5,
      duracion: 4,
      hidratacion: 3,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Cafeína', 'Ácido hialurónico'],
      libre_de: ['parabenos', 'fragancia'],
      contenido: '6 ml',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'rubor-durazno',
    name: 'Rubor en Crema',
    categoryId: 'rostro',
    summary: 'Rubor cremoso que se funde con la piel. Efecto “recién llegué de la playa”.',
    description:
      'Se aplica con los dedos, se difumina en segundos y deja un rubor fresco y natural. También funciona en labios y párpados.',
    images: [IMG.rubor, IMG.rubor2],
    variants: tones(52000, [
      ['Durazno', '#f0a07e'],
      ['Rosa', '#e58a99'],
      ['Coral', '#e8735f'],
    ]),
    attributes: {
      acabado: 'satinado',
      tipo_piel: ['seca', 'mixta'],
      cobertura: 3,
      duracion: 3,
      hidratacion: 4,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Escualano'],
      libre_de: ['parabenos'],
      contenido: '5 g',
    },
    badges: [],
    featured: true,
  }),
  p({
    id: 'polvo-iluminador',
    name: 'Iluminador Champagne',
    categoryId: 'rostro',
    summary: 'Destello fino que atrapa la luz sin purpurina.',
    description:
      'Un polvo prensado con perlas ultrafinas que da un brillo húmedo y elegante en pómulos, nariz y arco de cupido.',
    images: [IMG.iluminador, IMG.iluminador2],
    variants: tones(69000, [
      ['Champagne', '#ecd3a7'],
      ['Rosa dorado', '#e8b4a0'],
    ]),
    attributes: {
      acabado: 'luminoso',
      tipo_piel: ['todo'],
      cobertura: 2,
      duracion: 4,
      vegano: true,
      cruelty_free: true,
      libre_de: ['parabenos', 'fragancia'],
      contenido: '8 g',
    },
    badges: ['nuevo'],
    featured: true,
    createdAt: '2026-09-26T10:00:00.000Z',
  }),
  p({
    id: 'trio-rubores',
    name: 'Trío de Rubores',
    categoryId: 'rostro',
    summary: 'Rubor, contorno e iluminador en un solo estuche.',
    description:
      'Todo lo que necesitas para esculpir el rostro en un formato compacto con espejo. Ideal para llevar en el bolso.',
    images: [IMG.trio],
    variants: [{ id: 'unica', label: 'Estuche 3 tonos', price: 99000, stock: 5 }],
    attributes: {
      acabado: 'satinado',
      tipo_piel: ['todo'],
      cobertura: 3,
      duracion: 4,
      vegano: true,
      cruelty_free: true,
      libre_de: ['parabenos'],
      contenido: '3 × 3 g',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'serum-vitamina-c',
    name: 'Sérum Glow Vitamina C',
    categoryId: 'cuidado',
    summary: 'Vitamina C al 15 % para una piel luminosa y uniforme.',
    description:
      'Antioxidante, iluminador y unificador. Vitamina C estabilizada al 15 % con ácido ferúlico. Úsalo en la mañana antes del protector solar.',
    images: [IMG.serumC, IMG.serumC2],
    variants: [
      { id: 'ml15', label: '15 ml', price: 59000, stock: 10 },
      { id: 'ml30', label: '30 ml', price: 95000, stock: 8 },
    ],
    attributes: {
      acabado: 'luminoso',
      tipo_piel: ['todo'],
      hidratacion: 3,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Vitamina C 15 %', 'Ácido ferúlico', 'Vitamina E'],
      libre_de: ['parabenos', 'fragancia'],
      contenido: '30 ml',
    },
    badges: ['top'],
    featured: true,
  }),
  p({
    id: 'serum-hialuronico',
    name: 'Sérum Hialurónico',
    categoryId: 'cuidado',
    summary: 'Hidratación profunda con tres pesos de ácido hialurónico.',
    description:
      'Rellena, suaviza y prepara la piel para el maquillaje. Textura acuosa que se absorbe en segundos y no deja sensación pegajosa.',
    images: [IMG.hialuronico],
    variants: [{ id: 'ml30', label: '30 ml', price: 85000, stock: 12 }],
    attributes: {
      acabado: 'natural',
      tipo_piel: ['seca', 'sensible', 'mixta'],
      hidratacion: 5,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Ácido hialurónico', 'Pantenol'],
      libre_de: ['parabenos', 'fragancia', 'sulfatos'],
      contenido: '30 ml',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'crema-nube',
    name: 'Crema Nube',
    categoryId: 'cuidado',
    summary: 'Hidratante ligera como una nube, con ceramidas.',
    description:
      'Textura batida que hidrata sin engrasar. Ceramidas y centella asiática para reforzar la barrera de la piel.',
    images: [IMG.crema],
    variants: [{ id: 'ml50', label: '50 ml', price: 79000, stock: 0 }],
    attributes: {
      acabado: 'natural',
      tipo_piel: ['mixta', 'grasa', 'sensible'],
      hidratacion: 4,
      vegano: true,
      cruelty_free: true,
      ingredientes: ['Ceramidas', 'Centella asiática'],
      libre_de: ['parabenos', 'fragancia'],
      contenido: '50 ml',
    },
    badges: [],
    featured: false,
  }),
  p({
    id: 'set-brochas-pro',
    name: 'Set de Brochas Pro',
    categoryId: 'accesorios',
    summary: '10 brochas de fibra sintética suave con estuche.',
    description:
      'Las herramientas que usan nuestras maquilladoras: brochas para base, polvo, rubor, sombras y delineado, con fibras sintéticas veganas y mangos de madera.',
    images: [IMG.brochas, IMG.brochas2],
    variants: [{ id: 'set10', label: '10 piezas', price: 129000, compareAtPrice: 159000, stock: 7 }],
    attributes: {
      vegano: true,
      cruelty_free: true,
      contenido: '10 brochas + estuche',
    },
    badges: ['oferta'],
    featured: false,
  }),
]

export const lumiereTemplate: StoreSnapshot = {
  categories,
  products,
  config: {
    id: 'lumiere',
    business: {
      name: 'Lumière',
      tagline: 'Maquillaje consciente',
      logoText: 'Lumière',
      whatsapp: '573007654321',
      instagram: 'lumiere.beauty',
      email: 'hola@lumiere.demo',
      address: 'Cra. 37 #8A-24, El Poblado',
      city: 'Medellín',
      hours: 'Lun a sáb · 9:00 a 19:00',
      floatingWhatsapp: true,
      currency: 'COP',
      locale: 'es-CO',
    },
    theme: {
      mode: 'light',
      colors: {
        bg: '#fbf4ef',
        surface: '#ffffff',
        ink: '#2d1b21',
        muted: '#8a6d74',
        accent: '#b43c5f',
        accentInk: '#ffffff',
        line: '#efdfd8',
      },
      fonts: { display: 'Fraunces', body: 'Plus Jakarta Sans' },
      radius: 20,
      buttonShape: 'pill',
      displayWeight: 400,
      displayItalic: false,
      cardRatio: '4/5',
      cardStyle: 'boxed',
      grain: false,
      logoStyle: 'italic',
    },
    catalog: {
      productNoun: { singular: 'producto', plural: 'productos' },
      variantLabel: 'Tono',
      groups: [
        { id: 'desempeno', label: 'Desempeño', layout: 'meters' },
        { id: 'ideal', label: 'Ideal para', layout: 'chips' },
        { id: 'formula', label: 'Fórmula', layout: 'chips' },
        { id: 'ficha', label: 'Detalles', layout: 'list' },
      ],
      attributes: [
        {
          id: 'acabado',
          label: 'Acabado',
          type: 'select',
          filterable: true,
          showOnCard: true,
          group: 'ficha',
          options: [
            { value: 'mate', label: 'Mate' },
            { value: 'satinado', label: 'Satinado' },
            { value: 'gloss', label: 'Gloss' },
            { value: 'luminoso', label: 'Luminoso' },
            { value: 'natural', label: 'Natural' },
          ],
        },
        {
          id: 'tipo_piel',
          label: 'Tipo de piel',
          type: 'multi',
          filterable: true,
          group: 'ideal',
          options: [
            { value: 'todo', label: 'Todo tipo de piel' },
            { value: 'seca', label: 'Piel seca' },
            { value: 'mixta', label: 'Piel mixta' },
            { value: 'grasa', label: 'Piel grasa' },
            { value: 'sensible', label: 'Piel sensible' },
          ],
        },
        { id: 'cobertura', label: 'Cobertura', type: 'scale', max: 5, scaleLabels: ['Ligera', 'Alta'], group: 'desempeno', filterable: true },
        { id: 'duracion', label: 'Duración', type: 'scale', max: 5, scaleLabels: ['4 h', '16 h'], group: 'desempeno' },
        { id: 'hidratacion', label: 'Hidratación', type: 'scale', max: 5, scaleLabels: ['Baja', 'Alta'], group: 'desempeno' },
        { id: 'vegano', label: 'Vegano', type: 'boolean', filterable: true, group: 'formula' },
        { id: 'cruelty_free', label: 'Cruelty free', type: 'boolean', group: 'formula' },
        { id: 'ingredientes', label: 'Ingredientes clave', type: 'tags', group: 'formula' },
        {
          id: 'libre_de',
          label: 'Libre de',
          type: 'multi',
          group: 'formula',
          options: [
            { value: 'parabenos', label: 'Sin parabenos' },
            { value: 'fragancia', label: 'Sin fragancia' },
            { value: 'sulfatos', label: 'Sin sulfatos' },
            { value: 'siliconas', label: 'Sin siliconas' },
          ],
        },
        { id: 'contenido', label: 'Contenido', type: 'text', group: 'ficha' },
      ],
      badges: [
        { id: 'nuevo', label: 'Nuevo', tone: 'accent' },
        { id: 'top', label: 'Favorito', tone: 'ink' },
        { id: 'oferta', label: 'Oferta', tone: 'soft' },
      ],
    },
    sections: [
      {
        id: 'hero',
        type: 'hero',
        enabled: true,
        props: {
          layout: 'split',
          eyebrow: 'Maquillaje consciente · Hecho en Medellín',
          title: 'Tu piel, en su mejor día',
          subtitle:
            'Maquillaje vegano y cruelty free con tonos pensados para pieles latinas. Pide por WhatsApp y recíbelo hoy mismo en Medellín.',
          image: IMG.hero,
          ctaLabel: 'Comprar ahora',
          secondaryLabel: 'Encuentra tu tono',
        },
      },
      {
        id: 'marquee',
        type: 'marquee',
        enabled: true,
        props: { items: ['Cruelty free', '100 % vegano', 'Tonos para pieles latinas', 'Envíos a todo el país', 'Sin parabenos'] },
      },
      {
        id: 'categorias',
        type: 'categories',
        enabled: true,
        props: { title: 'Compra por categoría' },
      },
      {
        id: 'destacados',
        type: 'products',
        enabled: true,
        props: { title: 'Favoritos de la comunidad', subtitle: 'Lo que más repiten nuestras clientas.', source: 'featured', limit: 8 },
      },
      {
        id: 'historia',
        type: 'story',
        enabled: true,
        props: {
          eyebrow: 'Nuestra historia',
          title: 'Hecho para todos los tonos',
          body:
            'Lumière nació en un pequeño estudio de El Poblado porque no encontrábamos bases que funcionaran en nuestra piel. Hoy formulamos cada tono con maquilladoras locales y lo probamos en pieles reales antes de lanzarlo.',
          image: IMG.story,
          ctaLabel: 'Ver novedades',
        },
      },
      {
        id: 'nuevos',
        type: 'products',
        enabled: true,
        props: { title: 'Novedades', source: 'new', limit: 4 },
      },
      {
        id: 'beneficios',
        type: 'benefits',
        enabled: true,
        props: {
          items: [
            { icon: 'leaf', title: 'Vegano y cruelty free', text: 'Nunca probamos en animales.' },
            { icon: 'truck', title: 'Envío el mismo día', text: 'En Medellín, si pides antes de la 1 p. m.' },
            { icon: 'sparkles', title: 'Muestras en cada pedido', text: 'Para que pruebes algo nuevo.' },
            { icon: 'message', title: 'Te ayudamos con tu tono', text: 'Envíanos una foto y te recomendamos.' },
          ],
        },
      },
      {
        id: 'testimonios',
        type: 'testimonials',
        enabled: true,
        props: {
          title: 'Amor de verdad',
          items: [
            { quote: 'Por fin una base que no se me pone naranja. El tono 440 es exactamente mi piel.', author: 'Valentina P.', detail: 'Base Segunda Piel' },
            { quote: 'El Velvet Kiss Berry me duró toda la boda, incluso después de comer. Lo amo.', author: 'Camila T.', detail: 'Labial Velvet Kiss' },
            { quote: 'Pedí por WhatsApp a las 11 y a las 4 ya tenía mi pedido en casa.', author: 'Sara L.', detail: 'Domicilio Medellín' },
          ],
        },
      },
      {
        id: 'faq',
        type: 'faq',
        enabled: true,
        props: {
          title: 'Preguntas frecuentes',
          items: [
            { q: '¿Cómo sé cuál es mi tono?', a: 'Escríbenos por WhatsApp con una foto con luz natural y te recomendamos el tono ideal de base y corrector.' },
            { q: '¿Cómo hago un pedido?', a: 'Agrega tus productos a la bolsa y pulsa “Pedir por WhatsApp”. El mensaje se arma solo con tu pedido y te confirmamos en minutos.' },
            { q: '¿Sus productos son veganos?', a: 'La mayoría sí, y todos son cruelty free. En la ficha de cada producto verás su fórmula completa.' },
            { q: '¿Puedo cambiar un producto?', a: 'Sí, si está sellado tienes 15 días para cambiarlo por otro tono o producto.' },
          ],
        },
      },
      {
        id: 'cta',
        type: 'cta',
        enabled: true,
        props: {
          title: '¿Dudas con tu tono?',
          body: 'Envíanos una foto y una asesora te ayuda a elegir en minutos.',
          ctaLabel: 'Escribir por WhatsApp',
        },
      },
    ],
    checkout: {
      orderPrefix: 'LUM',
      greeting: 'Hola Lumière 💄 Quiero hacer este pedido:',
      closing: '¿Me confirman disponibilidad? ¡Gracias!',
      deliveryOptions: [
        { id: 'estudio', label: 'Recoger en el estudio', fee: 0, requiresAddress: false, note: 'El Poblado, Medellín' },
        { id: 'medellin', label: 'Domicilio en Medellín', fee: 8000, requiresAddress: true, note: 'Mismo día antes de la 1 p. m.', freeFrom: 150000 },
        { id: 'nacional', label: 'Envío nacional', fee: 15000, requiresAddress: true, note: '2 a 4 días hábiles', freeFrom: 150000 },
      ],
      paymentOptions: ['Transferencia o Nequi', 'Tarjeta (link de pago)', 'Efectivo contra entrega'],
    },
    announcements: ['Envío gratis por compras desde $150.000', 'Nuevo Gloss Cristal en 3 tonos', 'Muestras gratis en cada pedido'],
  },
}
